# Form implementation generated from reading ui file 'boxgroup.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(859, 884)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=Form)
        self.groupBox_3.setGeometry(QtCore.QRect(200, 10, 201, 81))
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    border: 2px solid rgb(0, 226, 166);\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 10px;\n"
"    background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 16px;\n"
"}\n"
"QGroupBox QLineEdit {\n"
"    border: 1px solid #aaa; /* Đổi màu viền của QLineEdit */\n"
"    border-radius: 5px; /* Làm tròn góc của QLineEdit */\n"
"    padding: 5px; /* Khoảng cách giữa viền và nội dung của QLineEdit */\n"
"    background-color: #333; /* Màu nền của QLineEdit */\n"
"    color: #fff; /* Màu chữ của QLineEdit */\n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 30, 51, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(130, 30, 51, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(90, 30, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Form)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 181, 81))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #666;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 10px;\n"
"    background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QGroupBox QLineEdit {\n"
"    border: 1px solid #aaa; /* Đổi màu viền của QLineEdit */\n"
"    border-radius: 5px; /* Làm tròn góc của QLineEdit */\n"
"    padding: 5px; /* Khoảng cách giữa viền và nội dung của QLineEdit */\n"
"    background-color: #333; /* Màu nền của QLineEdit */\n"
"    color: #fff; /* Màu chữ của QLineEdit */\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 30, 141, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=Form)
        self.groupBox_4.setGeometry(QtCore.QRect(410, 10, 151, 111))
        self.groupBox_4.setStyleSheet("QGroupBox {\n"
"    border: 2px solid rgb(170, 0, 0);\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 10px;\n"
"    background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QGroupBox QLineEdit {\n"
"    border: 1px solid #aaa; /* Đổi màu viền của QLineEdit */\n"
"    border-radius: 5px; /* Làm tròn góc của QLineEdit */\n"
"    padding: 5px; /* Khoảng cách giữa viền và nội dung của QLineEdit */\n"
"    background-color: #333; /* Màu nền của QLineEdit */\n"
"    color: #fff; /* Màu chữ của QLineEdit */\n"
"}")
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.groupBox_4)
        self.lineEdit_5.setGeometry(QtCore.QRect(20, 30, 51, 31))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.groupBox_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(80, 30, 51, 31))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.pushButton_16.setGeometry(QtCore.QRect(30, 70, 91, 31))
        self.pushButton_16.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_16.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/start.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_16.setIcon(icon)
        self.pushButton_16.setObjectName("pushButton_16")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_3.setTitle(_translate("Form", "Nghỉ"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Giây"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "%"))
        self.label.setText(_translate("Form", "+-"))
        self.groupBox_2.setTitle(_translate("Form", "Chrome"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Điền link tại đây"))
        self.groupBox_4.setTitle(_translate("Form", "Click"))
        self.lineEdit_5.setPlaceholderText(_translate("Form", "X"))
        self.lineEdit_6.setPlaceholderText(_translate("Form", "Y"))
        self.pushButton_16.setText(_translate("Form", "Chọn"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
