# Form implementation generated from reading ui file 'flowapp.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1287, 870)
        MainWindow.setStyleSheet("background-color: rgb(29, 29, 29);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_5 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_5.setStyleSheet("QWidget {\n"
"    background-color: rgb(20, 20, 20); /* Tối hơn để phù hợp với chủ đề tối */\n"
"    border-radius: 15px;\n"
"    font: 8pt \"MS Reference Sans Serif\";\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 10px;\n"
"    border: 2px solid #c2185b; /* Màu viền đỏ hồng đậm */\n"
"    background: linear-gradient(145deg, #ff4081, #c2185b); /* Gradient từ hồng nhạt đến đỏ đậm */\n"
"    color: #ffffff; /* Màu chữ trắng để dễ đọc */\n"
"    height: 40px;\n"
"    width: 120px;\n"
"    text-align: center; /* Sửa chính tả từ text-algin thành text-align */\n"
"    font-weight: bold; /* Chữ đậm để tạo ấn tượng */\n"
"    box-shadow: 4px 4px 8px rgba(0, 0, 0, 0.3); /* Đổ bóng cho nút bấm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #f50057; /* Màu viền hồng sáng hơn khi hover */\n"
"    background:#4A569D; /* Gradient sáng hơn khi hover */\n"
"    color: #ffffff; /* Đảm bảo màu chữ vẫn trắng khi hover */\n"
"    box-shadow: 4px 4px 12px rgba(0, 0, 0, 0.4); /* Đổ bóng nổi bật hơn khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: linear-gradient(145deg, #d81b60, #c2185b); /* Gradient tối hơn khi nhấn */\n"
"    border: 2px solid #b71c1c; /* Màu viền đỏ đậm hơn khi nhấn */\n"
"    box-shadow: inset 4px 4px 8px rgba(0, 0, 0, 0.5); /* Hiệu ứng đổ bóng lõm khi nhấn */\n"
"}\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_19 = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton_19.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/stop.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_19.setIcon(icon)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_3.addWidget(self.pushButton_19, 0, 0, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton_18.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/load.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_18.setIcon(icon1)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_3.addWidget(self.pushButton_18, 0, 1, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton_17.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/sellect.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_17.setIcon(icon2)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_3.addWidget(self.pushButton_17, 0, 2, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton_16.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_16.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/start.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_16.setIcon(icon3)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_3.addWidget(self.pushButton_16, 0, 3, 1, 1)
        self.gridLayout_4.addWidget(self.widget_5, 0, 1, 1, 2)
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setStyleSheet("QWidget {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(0, 128, 255); /* Thay đổi màu sắc và độ dày của border */\n"
"    padding: 10px; /* Thêm padding để tạo khoảng cách giữa nội dung và viền */\n"
"    font-family: \"Courier New\", Courier, monospace; /* Sử dụng phông chữ monospace cho mã nguồn */\n"
"    font-size: 12px; /* Cỡ chữ phù hợp với việc hiển thị mã nguồn */\n"
"    color: rgb(0, 0, 0); /* Màu chữ */\n"
"    selection-background-color: rgb(0, 128, 255); /* Màu nền khi chọn văn bản */\n"
"    selection-color: rgb(255, 255, 255); /* Màu chữ khi chọn văn bản */\n"
"    border-image: none; /* Không sử dụng border image */\n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit = QtWidgets.QTextEdit(parent=self.widget_2)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_2.addWidget(self.textEdit)
        self.gridLayout_4.addWidget(self.widget_2, 1, 2, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(318, 418, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_4.setStyleSheet("QWidget{\n"
"background-color: rgb(206, 206, 206);\n"
"border-radius: 8px;\n"
"font: 8pt \"MS Reference Sans Serif\";\n"
"width: 10px;\n"
"height: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"    border-radius: 7px;\n"
"    border: 2px solid #c2185b; /* Màu viền đỏ hồng đậm */\n"
"    background: linear-gradient(145deg, #ff4081, #c2185b); /* Gradient từ hồng nhạt đến đỏ đậm */\n"
"    color: rgb(0, 0, 0);\n"
"    height: 20px;\n"
"    text-align: center; /* Sửa chính tả từ text-algin thành text-align */\n"
"    font-weight: bold; /* Chữ đậm để tạo ấn tượng */\n"
"    box-shadow: 4px 4px 8px rgba(0, 0, 0, 0.3); /* Đổ bóng cho nút bấm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #f50057; /* Màu viền hồng sáng hơn khi hover */\n"
"    background:#4A569D; /* Gradient sáng hơn khi hover */\n"
"    color: #ffffff; /* Đảm bảo màu chữ vẫn trắng khi hover */\n"
"    box-shadow: 4px 4px 12px rgba(0, 0, 0, 0.4); /* Đổ bóng nổi bật hơn khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: linear-gradient(145deg, #d81b60, #c2185b); /* Gradient tối hơn khi nhấn */\n"
"    border: 2px solid #b71c1c; /* Màu viền đỏ đậm hơn khi nhấn */\n"
"    box-shadow: inset 4px 4px 8px rgba(0, 0, 0, 0.5); /* Hiệu ứng đổ bóng lõm khi nhấn */\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout.setObjectName("gridLayout")
        self.chrome = QtWidgets.QGroupBox(parent=self.widget_4)
        self.chrome.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.chrome.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #666;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 10px;\n"
"    background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 16px;\n"
"}\n"
"QLineEdit {\n"
"    border: 1px solid #aaa; /* Đổi màu viền của QLineEdit */\n"
"    border-radius: 5px; /* Làm tròn góc của QLineEdit */\n"
"    padding: 5px; /* Khoảng cách giữa viền và nội dung của QLineEdit */\n"
"    background-color: #333; /* Màu nền của QLineEdit */\n"
"    color: #fff; /* Màu chữ của QLineEdit */\n"
"}")
        self.chrome.setObjectName("chrome")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.chrome)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit_12 = QtWidgets.QLineEdit(parent=self.chrome)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_5.addWidget(self.lineEdit_12, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.chrome)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_5.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.chrome, 1, 0, 1, 1)
        self.sleep = QtWidgets.QGroupBox(parent=self.widget_4)
        self.sleep.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.sleep.setStyleSheet("QGroupBox {\n"
"    border: 2px solid rgb(0, 226, 166);\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 10px;\n"
"    background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 16px;\n"
"}\n"
"QGroupBox QLineEdit {\n"
"    border: 1px solid #aaa; /* Đổi màu viền của QLineEdit */\n"
"    border-radius: 5px; /* Làm tròn góc của QLineEdit */\n"
"    padding: 5px; /* Khoảng cách giữa viền và nội dung của QLineEdit */\n"
"    background-color: #333; /* Màu nền của QLineEdit */\n"
"    color: #fff; /* Màu chữ của QLineEdit */\n"
"}")
        self.sleep.setObjectName("sleep")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.sleep)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.sleep)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_6.addWidget(self.pushButton_4, 1, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(parent=self.sleep)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 1, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(parent=self.sleep)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_6.addWidget(self.lineEdit_8, 0, 2, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=self.sleep)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_6.addWidget(self.lineEdit_7, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.sleep, 1, 1, 1, 1)
        self.click_2 = QtWidgets.QGroupBox(parent=self.widget_4)
        self.click_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.click_2.setStyleSheet("QGroupBox {\n"
"    border: 2px solid rgb(170, 0, 0);\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 10px;\n"
"    background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QGroupBox QLineEdit {\n"
"    border: 1px solid #aaa; /* Đổi màu viền của QLineEdit */\n"
"    border-radius: 5px; /* Làm tròn góc của QLineEdit */\n"
"    padding: 5px; /* Khoảng cách giữa viền và nội dung của QLineEdit */\n"
"    background-color: #333; /* Màu nền của QLineEdit */\n"
"    color: #fff; /* Màu chữ của QLineEdit */\n"
"}")
        self.click_2.setObjectName("click_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.click_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(parent=self.click_2)
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_8.addWidget(self.lineEdit_9, 2, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(parent=self.click_2)
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_8.addWidget(self.lineEdit_10, 2, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.click_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_8.addWidget(self.pushButton_5, 3, 0, 1, 2)
        self.gridLayout.addWidget(self.click_2, 1, 4, 1, 1)
        self.click = QtWidgets.QGroupBox(parent=self.widget_4)
        self.click.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.click.setStyleSheet("QGroupBox {\n"
"    border: 2px solid rgb(170, 0, 0);\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 10px;\n"
"    background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QGroupBox QLineEdit {\n"
"    border: 1px solid #aaa; /* Đổi màu viền của QLineEdit */\n"
"    border-radius: 5px; /* Làm tròn góc của QLineEdit */\n"
"    padding: 5px; /* Khoảng cách giữa viền và nội dung của QLineEdit */\n"
"    background-color: #333; /* Màu nền của QLineEdit */\n"
"    color: #fff; /* Màu chữ của QLineEdit */\n"
"}")
        self.click.setObjectName("click")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.click)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.click)
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_7.addWidget(self.lineEdit_6, 2, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.click)
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_7.addWidget(self.lineEdit_5, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.click)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_7.addWidget(self.pushButton, 3, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.click)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_7.addWidget(self.pushButton_2, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.click, 1, 3, 1, 1)
        self.gridLayout_2.addWidget(self.widget_4, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_19.setText(_translate("MainWindow", "Chạy thử"))
        self.pushButton_18.setText(_translate("MainWindow", "Xóa"))
        self.pushButton_17.setText(_translate("MainWindow", "Lưu"))
        self.pushButton_16.setText(_translate("MainWindow", "Thoát"))
        self.chrome.setTitle(_translate("MainWindow", "Chrome"))
        self.lineEdit_12.setPlaceholderText(_translate("MainWindow", "Điền link tại đây"))
        self.pushButton_3.setText(_translate("MainWindow", "Add"))
        self.sleep.setTitle(_translate("MainWindow", "Sleep"))
        self.pushButton_4.setText(_translate("MainWindow", "Add"))
        self.label_2.setText(_translate("MainWindow", "+-"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "s"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "s"))
        self.click_2.setTitle(_translate("MainWindow", "Keyboard"))
        self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "Text"))
        self.lineEdit_10.setPlaceholderText(_translate("MainWindow", "delay"))
        self.pushButton_5.setText(_translate("MainWindow", "Add"))
        self.click.setTitle(_translate("MainWindow", "Click"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "Y"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "X"))
        self.pushButton.setText(_translate("MainWindow", "Add"))
        self.pushButton_2.setText(_translate("MainWindow", "Get"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
