# Form implementation generated from reading ui file 'flowapp.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1082, 739)
        MainWindow.setStyleSheet("background-color: rgb(29, 29, 29);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_4 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_4.setStyleSheet("QWidget{\n"
"background-color: rgb(206, 206, 206);\n"
"border-radius: 15px;\n"
"font: 8pt \"MS Reference Sans Serif\";\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 12px;\n"
"    border: 2px solid #2ecc71; /* Màu viền xanh lá sáng */\n"
"    background-color: #ffffff; /* Nền màu trắng sáng */\n"
"    color: #2c3e50; /* Màu chữ tối để tạo sự tương phản tốt */\n"
"    height: 25px;\n"
"    width: 140px;\n"
"    text-align: center; /* Sửa lỗi chính tả từ \'text-algin\' thành \'text-align\' */\n"
"    font-weight: bold; /* Chữ đậm để nổi bật hơn */\n"
"    font-size: 14px; /* Kích thước chữ phù hợp */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #16a085; /* Màu viền khi hover đậm hơn */\n"
"    background-color: #e8f6f3; /* Nền màu xanh lục nhạt hơn khi hover */\n"
"    color: #27ae60; /* Màu chữ khi hover đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e0e0e0; /* Nền màu xám nhạt khi nhấn */\n"
"    border: 2px solid #3498db; /* Màu viền khi nhấn */\n"
"    color: #2c3e50; /* Màu chữ khi nhấn */\n"
"}\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.widget_4)
        self.pushButton_14.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_14.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/start.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_14.setIcon(icon)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 2, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.widget_4)
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/sellect.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_11.setIcon(icon1)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 0, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.widget_4)
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/load.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_12.setIcon(icon2)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 3, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.widget_4)
        self.pushButton_13.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/stop.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_13.setIcon(icon3)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget_4, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(38, 628, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 2, 1)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 3px solid;\n"
"border-color: rgb(120, 80, 0);\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout_4.addWidget(self.widget, 1, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setStyleSheet("QWidget {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(0, 128, 255); /* Thay đổi màu sắc và độ dày của border */\n"
"    padding: 10px; /* Thêm padding để tạo khoảng cách giữa nội dung và viền */\n"
"    font-family: \"Courier New\", Courier, monospace; /* Sử dụng phông chữ monospace cho mã nguồn */\n"
"    font-size: 12px; /* Cỡ chữ phù hợp với việc hiển thị mã nguồn */\n"
"    color: rgb(0, 0, 0); /* Màu chữ */\n"
"    selection-background-color: rgb(0, 128, 255); /* Màu nền khi chọn văn bản */\n"
"    selection-color: rgb(255, 255, 255); /* Màu chữ khi chọn văn bản */\n"
"    border-image: none; /* Không sử dụng border image */\n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit = QtWidgets.QTextEdit(parent=self.widget_2)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_2.addWidget(self.textEdit)
        self.gridLayout_4.addWidget(self.widget_2, 1, 2, 1, 1)
        self.widget_5 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_5.setStyleSheet("QWidget {\n"
"    background-color: rgb(20, 20, 20); /* Tối hơn để phù hợp với chủ đề tối */\n"
"    border-radius: 15px;\n"
"    font: 8pt \"MS Reference Sans Serif\";\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 10px;\n"
"    border: 2px solid #c2185b; /* Màu viền đỏ hồng đậm */\n"
"    background: linear-gradient(145deg, #ff4081, #c2185b); /* Gradient từ hồng nhạt đến đỏ đậm */\n"
"    color: #ffffff; /* Màu chữ trắng để dễ đọc */\n"
"    height: 40px;\n"
"    width: 120px;\n"
"    text-align: center; /* Sửa chính tả từ text-algin thành text-align */\n"
"    font-weight: bold; /* Chữ đậm để tạo ấn tượng */\n"
"    box-shadow: 4px 4px 8px rgba(0, 0, 0, 0.3); /* Đổ bóng cho nút bấm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #f50057; /* Màu viền hồng sáng hơn khi hover */\n"
"    background:#4A569D; /* Gradient sáng hơn khi hover */\n"
"    color: #ffffff; /* Đảm bảo màu chữ vẫn trắng khi hover */\n"
"    box-shadow: 4px 4px 12px rgba(0, 0, 0, 0.4); /* Đổ bóng nổi bật hơn khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: linear-gradient(145deg, #d81b60, #c2185b); /* Gradient tối hơn khi nhấn */\n"
"    border: 2px solid #b71c1c; /* Màu viền đỏ đậm hơn khi nhấn */\n"
"    box-shadow: inset 4px 4px 8px rgba(0, 0, 0, 0.5); /* Hiệu ứng đổ bóng lõm khi nhấn */\n"
"}\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_19 = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton_19.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_19.setIcon(icon3)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_3.addWidget(self.pushButton_19, 0, 0, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton_18.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_18.setIcon(icon2)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_3.addWidget(self.pushButton_18, 0, 1, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton_17.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_17.setIcon(icon1)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_3.addWidget(self.pushButton_17, 0, 2, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton_16.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_16.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_16.setIcon(icon)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_3.addWidget(self.pushButton_16, 0, 3, 1, 1)
        self.gridLayout_4.addWidget(self.widget_5, 0, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_14.setText(_translate("MainWindow", "Nghỉ"))
        self.pushButton_11.setText(_translate("MainWindow", "Mở Chrome"))
        self.pushButton_12.setText(_translate("MainWindow", "Thoát"))
        self.pushButton_13.setText(_translate("MainWindow", "Thêm Cookie"))
        self.pushButton_19.setText(_translate("MainWindow", "Chạy thử"))
        self.pushButton_18.setText(_translate("MainWindow", "Xóa"))
        self.pushButton_17.setText(_translate("MainWindow", "Lưu"))
        self.pushButton_16.setText(_translate("MainWindow", "Thoát"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
