# Form implementation generated from reading ui file 'mainui_v2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1863, 891)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/logo-iart.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgba(255, 255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setEnabled(True)
        self.widget.setStyleSheet("QWidget{\n"
"background-color: rgb(0, 0, 0);\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"color:white;\n"
"text-align:center;\n"
"height: 36px;\n"
"border:none;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 127);\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 255, 255); /* Màu nền khi hover */\n"
"    border-color: rgb(0, 150, 255); /* Màu viền khi hover */\n"
"    color: rgb(0, 0, 0); /* Màu chữ khi hover */\n"
"    transform: scale(1.05); /* Tăng kích thước khi hover */\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.2); /* Bóng đổ khi hover */\n"
"}")
        self.widget.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/dashboard.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setCheckable(True)
        self.pushButton.setAutoExclusive(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/scripts.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setAutoExclusive(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/map.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setAutoExclusive(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_4.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/setting.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setAutoExclusive(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(28, 556, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setEnabled(True)
        self.label_2.setText("")
        self.label_2.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_2.setPixmap(QtGui.QPixmap("img/logo-iart (1).png"))
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setStyleSheet("QWidget {\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"background-color: rgb(0, 0, 0)\n"
"}\n"
"\n"
"QPushButton {\n"
"background-clip: padding-box;\n"
"color:white;\n"
"text-align:left;\n"
"height: 36px;\n"
"border:none;\n"
"padding-left:20px;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"font: 57 12pt \"Dubai Medium\";\n"
"}\n"
"QPushButton:checked{\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 127);\n"
"font-weight:bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 255, 255); /* Màu nền khi hover */\n"
"    border-color: rgb(0, 150, 255); /* Màu viền khi hover */\n"
"    color: rgb(0, 0, 0); /* Màu chữ khi hover */\n"
"    transform: scale(1.05); /* Tăng kích thước khi hover */\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.2); /* Bóng đổ khi hover */\n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(30)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_5.setIcon(icon1)
        self.pushButton_5.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setAutoExclusive(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_6.setIcon(icon2)
        self.pushButton_6.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setAutoExclusive(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_7.setIcon(icon3)
        self.pushButton_7.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setAutoExclusive(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_8.setIcon(icon4)
        self.pushButton_8.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_8.setCheckable(True)
        self.pushButton_8.setAutoExclusive(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_2.addWidget(self.pushButton_8)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(28, 520, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(parent=self.widget_2)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/logo-iart2.png"))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.gridLayout_2.addWidget(self.widget_2, 0, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.widget_3)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"color:white;\n"
"text-align:left;\n"
"height: 30px;\n"
"border:none;\n"
"}")
        self.pushButton_9.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/more.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_9.setIcon(icon5)
        self.pushButton_9.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout.addWidget(self.pushButton_9)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget_3)
        self.lineEdit.setStyleSheet("border: none;\n"
"color: rgb(255, 0, 0);\n"
"font: 75 italic 13pt \"Arial\";")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.widget_3)
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"color:white;\n"
"text-align:left;\n"
"height: 30px;\n"
"border:none;\n"
"}")
        self.pushButton_10.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("img/logout.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_10.setIcon(icon6)
        self.pushButton_10.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_10.setCheckable(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout.addWidget(self.pushButton_10)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.widget_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.dashboard = QtWidgets.QWidget()
        self.dashboard.setObjectName("dashboard")
        self.gridLayout = QtWidgets.QGridLayout(self.dashboard)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.dashboard)
        self.tableWidget.setStyleSheet("height:300px;")
        self.tableWidget.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_4 = QtWidgets.QWidget(parent=self.dashboard)
        self.widget_4.setStyleSheet("QWidget{\n"
"font: 8pt \"MS Reference Sans Serif\";\n"
"}\n"
"\n"
"QPushButton{\n"
"border-radius:10px;\n"
"border: 2px solid #23074d;\n"
"background-color: #cc5333;\n"
"color:#FFB6C1;\n"
"height: 40px;\n"
"width: 120px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #009fff ;\n"
"    background-color:#23074d;\n"
"            }\n"
"QPushButton:pressed {\n"
"                background-color: #5650de; /* Màu nền khi nhấn */\n"
"            }\n"
"\n"
"QComboBox{\n"
"background-color: rgb(85, 255, 127);\n"
"border-radius: 5px;\n"
"border: 2px solid #23074d;\n"
"height:40px;\n"
"width: 105px;\n"
"}\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.comboBox = QtWidgets.QComboBox(parent=self.widget_4)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_6.addWidget(self.comboBox)
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.widget_4)
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("img/sellect.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_11.setIcon(icon7)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_6.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.widget_4)
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("img/load.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_12.setIcon(icon8)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_6.addWidget(self.pushButton_12)
        self.horizontalLayout_3.addWidget(self.widget_4)
        self.widget_15 = QtWidgets.QWidget(parent=self.dashboard)
        self.widget_15.setStyleSheet("QWidget{\n"
"font: 8pt \"MS Reference Sans Serif\";\n"
"}\n"
"\n"
"QPushButton{\n"
"border-radius:10px;\n"
"border: 2px solid #23074d;\n"
"background-color: #cc5333;\n"
"color:#FFB6C1;\n"
"height: 40px;\n"
"width: 120px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #009fff ;\n"
"    background-color:#23074d;\n"
"            }\n"
"QPushButton:pressed {\n"
"                background-color: #5650de; /* Màu nền khi nhấn */\n"
"            }\n"
"\n"
"QComboBox{\n"
"background-color: rgb(85, 255, 127);\n"
"border-radius: 5px;\n"
"border: 2px solid #23074d;\n"
"height:40px;\n"
"width: 105px;\n"
"}\n"
"")
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_8.addItem(spacerItem3)
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.widget_15)
        self.pushButton_13.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("img/stop.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_13.setIcon(icon9)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_8.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.widget_15)
        self.pushButton_14.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("img/start.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_14.setIcon(icon10)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_8.addWidget(self.pushButton_14)
        self.horizontalLayout_3.addWidget(self.widget_15)
        self.widget_5 = QtWidgets.QWidget(parent=self.dashboard)
        self.widget_5.setStyleSheet("QWidget {\n"
"border-radius:10px;\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(170, 0, 0)\n"
"}")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit = QtWidgets.QTextEdit(parent=self.widget_5)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_2.addWidget(self.textEdit)
        self.horizontalLayout_3.addWidget(self.widget_5)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.dashboard)
        self.system = QtWidgets.QWidget()
        self.system.setObjectName("system")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.system)
        self.gridLayout_23.setObjectName("gridLayout_23")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_23.addItem(spacerItem4, 0, 3, 1, 1)
        self.widget_7 = QtWidgets.QWidget(parent=self.system)
        self.widget_7.setStyleSheet("QWidget {\n"
"    border:None\n"
"}\n"
"")
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_8.addItem(spacerItem5, 0, 3, 1, 1)
        self.textEdit_3 = QtWidgets.QTextEdit(parent=self.widget_7)
        self.textEdit_3.setStyleSheet("QTextEdit {\n"
"    \n"
"    font: 57 8pt \"Dubai Medium\";\n"
"    background-color: rgb(255, 255, 255); /* Màu nền của QTextEdit */\n"
"    border-radius: 7px;\n"
"    border: 2px solid rgb(0, 80, 118); /* Đường viền */\n"
"    color: rgb(0, 0, 0); /* Màu chữ */\n"
"    selection-background-color: rgb(0, 128, 255); /* Màu nền khi chọn văn bản */\n"
"    selection-color: rgb(255, 255, 255); /* Màu chữ khi chọn văn bản */\n"
"}\n"
"\n"
"/* Tùy chỉnh thanh cuộn khi QTextEdit hiển thị thanh cuộn */\n"
"QTextEdit QScrollBar:vertical {\n"
"    background-color: rgb(240, 240, 240); /* Màu nền thanh cuộn */\n"
"    width: 12px; /* Độ rộng của thanh cuộn */\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 6px; /* Bo góc cho thanh cuộn */\n"
"}\n"
"\n"
"QTextEdit QScrollBar::handle:vertical {\n"
"    background-color: rgb(0, 80, 118); /* Màu thanh cuộn */\n"
"    min-height: 20px;\n"
"    border-radius: 6px; /* Bo góc cho thanh cuộn */\n"
"}\n"
"\n"
"QTextEdit QScrollBar::handle:vertical:hover {\n"
"    background-color: rgb(0, 128, 255); /* Màu thanh cuộn khi hover */\n"
"}\n"
"\n"
"QTextEdit QScrollBar::add-line:vertical, QTextEdit QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QTextEdit QScrollBar::add-page:vertical, QTextEdit QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* Tương tự cho thanh cuộn ngang nếu cần */\n"
"QTextEdit QScrollBar:horizontal {\n"
"    background-color: rgb(240, 240, 240); /* Màu nền thanh cuộn */\n"
"    height: 12px;\n"
"    margin: 0 15px 0 15px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QTextEdit QScrollBar::handle:horizontal {\n"
"    background-color: rgb(0, 80, 118); /* Màu thanh cuộn ngang */\n"
"    min-width: 20px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QTextEdit QScrollBar::handle:horizontal:hover {\n"
"    background-color: rgb(0, 128, 255); /* Màu thanh cuộn khi hover */\n"
"}\n"
"\n"
"QTextEdit QScrollBar::add-line:horizontal, QTextEdit QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: none;\n"
"    width: 0px;\n"
"}\n"
"\n"
"QTextEdit QScrollBar::add-page:horizontal, QTextEdit QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"")
        self.textEdit_3.setObjectName("textEdit_3")
        self.gridLayout_8.addWidget(self.textEdit_3, 2, 2, 1, 4)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.widget_7)
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 2px solid rgb(0, 80, 118);\n"
"    color: rgb(0, 0, 0);\n"
"    selection-background-color: rgb(0, 128, 255);\n"
"    selection-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(230, 230, 230); /* Màu nền thanh cuộn */\n"
"    width: 12px;\n"
"    margin: 15px 0 15px 0; /* Khoảng cách giữa đầu và cuối thanh cuộn */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: rgb(0, 80, 118); /* Màu thanh cuộn */\n"
"    min-height: 20px; /* Chiều cao tối thiểu của thanh cuộn */\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(230, 230, 230); /* Màu nền thanh cuộn ngang */\n"
"    height: 12px;\n"
"    margin: 0 15px 0 15px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(0, 80, 118); /* Màu thanh cuộn ngang */\n"
"    min-width: 20px; /* Chiều rộng tối thiểu của thanh cuộn ngang */\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: none;\n"
"    width: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"QPushButton {\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(0, 128, 255); /* Thay đổi màu sắc và độ dày của border */\n"
"    padding: 10px; /* Thêm padding để tạo khoảng cách giữa nội dung và viền */\n"
"    \n"
"    \n"
"    \n"
"    font: 57 9pt \"Dubai Medium\";\n"
"}\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 241, 675))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_7.addItem(spacerItem6, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_8.addWidget(self.scrollArea, 2, 0, 1, 2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_8.addItem(spacerItem7, 0, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_8.addItem(spacerItem8, 0, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_8.addItem(spacerItem9, 0, 5, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_8.addItem(spacerItem10, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.widget_7, 2, 1, 1, 3)
        self.widget_6 = QtWidgets.QWidget(parent=self.system)
        self.widget_6.setStyleSheet("QWidget {\n"
"    background-color: rgb(20, 20, 20); /* Tối hơn để phù hợp với chủ đề tối */\n"
"    border-radius: 15px;\n"
"    font: 8pt \"MS Reference Sans Serif\";\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 10px;\n"
"    border: 2px solid #c2185b; /* Màu viền đỏ hồng đậm */\n"
"    background: linear-gradient(145deg, #ff4081, #c2185b); /* Gradient từ hồng nhạt đến đỏ đậm */\n"
"    color: #ffffff; /* Màu chữ trắng để dễ đọc */\n"
"    height: 40px;\n"
"    width: 120px;\n"
"    text-align: center; /* Sửa chính tả từ text-algin thành text-align */\n"
"    font-weight: bold; /* Chữ đậm để tạo ấn tượng */\n"
"    box-shadow: 4px 4px 8px rgba(0, 0, 0, 0.3); /* Đổ bóng cho nút bấm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #f50057; /* Màu viền hồng sáng hơn khi hover */\n"
"    background:rgb(255, 229, 241);\n"
"    color: rgb(80, 85, 255);\n"
"    box-shadow: 4px 4px 12px rgba(0, 0, 0, 0.4); /* Đổ bóng nổi bật hơn khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: linear-gradient(145deg, #d81b60, #c2185b); /* Gradient tối hơn khi nhấn */\n"
"    border: 2px solid #b71c1c; /* Màu viền đỏ đậm hơn khi nhấn */\n"
"    box-shadow: inset 4px 4px 8px rgba(0, 0, 0, 0.5); /* Hiệu ứng đổ bóng lõm khi nhấn */\n"
"}\n"
"")
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.pushButton_22 = QtWidgets.QPushButton(parent=self.widget_6)
        self.pushButton_22.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("img/run_test.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_22.setIcon(icon11)
        self.pushButton_22.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_14.addWidget(self.pushButton_22, 0, 1, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(parent=self.widget_6)
        self.pushButton_23.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("img/back.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_23.setIcon(icon12)
        self.pushButton_23.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_14.addWidget(self.pushButton_23, 0, 3, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(parent=self.widget_6)
        self.pushButton_25.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_25.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("img/delete.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_25.setIcon(icon13)
        self.pushButton_25.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_14.addWidget(self.pushButton_25, 0, 5, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(parent=self.widget_6)
        self.pushButton_24.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("img/save.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_24.setIcon(icon14)
        self.pushButton_24.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_14.addWidget(self.pushButton_24, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.widget_6, 1, 2, 1, 2)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.tabWidget_2 = QtWidgets.QTabWidget(parent=self.system)
        self.tabWidget_2.setStyleSheet("")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_14 = QtWidgets.QWidget(parent=self.tab)
        self.widget_14.setStyleSheet("QWidget{\n"
"background-color: rgb(206, 206, 206);\n"
"border-radius: 8px;\n"
"font: 8pt \"MS Reference Sans Serif\";\n"
"width: 10px;\n"
"height: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"    border-radius: 7px;\n"
"    border: 2px solid #c2185b; /* Màu viền đỏ hồng đậm */\n"
"    background: linear-gradient(145deg, #ff4081, #c2185b); /* Gradient từ hồng nhạt đến đỏ đậm */\n"
"    color: rgb(0, 0, 0);\n"
"    height: 20px;\n"
"    text-align: center; /* Sửa chính tả từ text-algin thành text-align */\n"
"    font-weight: bold; /* Chữ đậm để tạo ấn tượng */\n"
"    box-shadow: 4px 4px 8px rgba(0, 0, 0, 0.3); /* Đổ bóng cho nút bấm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #f50057; /* Màu viền hồng sáng hơn khi hover */\n"
"    background:#4A569D; /* Gradient sáng hơn khi hover */\n"
"    color: #ffffff; /* Đảm bảo màu chữ vẫn trắng khi hover */\n"
"    box-shadow: 4px 4px 12px rgba(0, 0, 0, 0.4); /* Đổ bóng nổi bật hơn khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: linear-gradient(145deg, #d81b60, #c2185b); /* Gradient tối hơn khi nhấn */\n"
"    border: 2px solid #b71c1c; /* Màu viền đỏ đậm hơn khi nhấn */\n"
"    box-shadow: inset 4px 4px 8px rgba(0, 0, 0, 0.5); /* Hiệu ứng đổ bóng lõm khi nhấn */\n"
"}\n"
"\n"
"\n"
"QGroupBox {\n"
"    border: 2px solid rgb(118, 0, 88);\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 3 10px;\n"
"    background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 16px;\n"
"}\n"
"QLineEdit {\n"
"    border: 1px solid #aaa; /* Đổi màu viền của QLineEdit */\n"
"    border-radius: 5px; /* Làm tròn góc của QLineEdit */\n"
"    padding: 5px; /* Khoảng cách giữa viền và nội dung của QLineEdit */\n"
"    background-color: #333; /* Màu nền của QLineEdit */\n"
"    color: #fff; /* Màu chữ của QLineEdit */\n"
"}")
        self.widget_14.setObjectName("widget_14")
        self.gridLayout_42 = QtWidgets.QGridLayout(self.widget_14)
        self.gridLayout_42.setObjectName("gridLayout_42")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_42.addItem(spacerItem11, 0, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_42.addItem(spacerItem12, 0, 2, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_42.addItem(spacerItem13, 0, 3, 1, 1)
        self.chrome_8 = QtWidgets.QGroupBox(parent=self.widget_14)
        self.chrome_8.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.chrome_8.setStyleSheet("")
        self.chrome_8.setObjectName("chrome_8")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.chrome_8)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.pushButton_28 = QtWidgets.QPushButton(parent=self.chrome_8)
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout_20.addWidget(self.pushButton_28, 1, 0, 1, 3)
        self.lineEdit_20 = QtWidgets.QLineEdit(parent=self.chrome_8)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_20.addWidget(self.lineEdit_20, 0, 0, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(parent=self.chrome_8)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_20.addWidget(self.lineEdit_21, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.chrome_8)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_20.addWidget(self.label_6, 0, 1, 1, 1)
        self.gridLayout_42.addWidget(self.chrome_8, 1, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_42.addItem(spacerItem14, 0, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_42.addItem(spacerItem15, 3, 2, 1, 1)
        self.chrome_7 = QtWidgets.QGroupBox(parent=self.widget_14)
        self.chrome_7.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.chrome_7.setStyleSheet("")
        self.chrome_7.setObjectName("chrome_7")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.chrome_7)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.pushButton_27 = QtWidgets.QPushButton(parent=self.chrome_7)
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout_19.addWidget(self.pushButton_27, 1, 0, 1, 2)
        self.lineEdit_19 = QtWidgets.QLineEdit(parent=self.chrome_7)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_19.addWidget(self.lineEdit_19, 0, 0, 1, 2)
        self.gridLayout_42.addWidget(self.chrome_7, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.widget_14, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.widget_11 = QtWidgets.QWidget(parent=self.tab_4)
        self.widget_11.setStyleSheet("QWidget{\n"
"background-color: rgb(206, 206, 206);\n"
"border-radius: 8px;\n"
"font: 8pt \"MS Reference Sans Serif\";\n"
"width: 10px;\n"
"height: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"    border-radius: 7px;\n"
"    border: 2px solid #c2185b; /* Màu viền đỏ hồng đậm */\n"
"    background: linear-gradient(145deg, #ff4081, #c2185b); /* Gradient từ hồng nhạt đến đỏ đậm */\n"
"    color: rgb(0, 0, 0);\n"
"    height: 20px;\n"
"    text-align: center; /* Sửa chính tả từ text-algin thành text-align */\n"
"    font-weight: bold; /* Chữ đậm để tạo ấn tượng */\n"
"    box-shadow: 4px 4px 8px rgba(0, 0, 0, 0.3); /* Đổ bóng cho nút bấm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #f50057; /* Màu viền hồng sáng hơn khi hover */\n"
"    background:#4A569D; /* Gradient sáng hơn khi hover */\n"
"    color: #ffffff; /* Đảm bảo màu chữ vẫn trắng khi hover */\n"
"    box-shadow: 4px 4px 12px rgba(0, 0, 0, 0.4); /* Đổ bóng nổi bật hơn khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: linear-gradient(145deg, #d81b60, #c2185b); /* Gradient tối hơn khi nhấn */\n"
"    border: 2px solid #b71c1c; /* Màu viền đỏ đậm hơn khi nhấn */\n"
"    box-shadow: inset 4px 4px 8px rgba(0, 0, 0, 0.5); /* Hiệu ứng đổ bóng lõm khi nhấn */\n"
"}\n"
"\n"
"\n"
"QGroupBox {\n"
"    border: 2px solid rgb(0, 170, 0);\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 3 10px;\n"
"    background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 16px;\n"
"}\n"
"QLineEdit {\n"
"    border: 1px solid #aaa; /* Đổi màu viền của QLineEdit */\n"
"    border-radius: 5px; /* Làm tròn góc của QLineEdit */\n"
"    padding: 5px; /* Khoảng cách giữa viền và nội dung của QLineEdit */\n"
"    background-color: #333; /* Màu nền của QLineEdit */\n"
"    color: #fff; /* Màu chữ của QLineEdit */\n"
"}")
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.widget_11)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.chrome_6 = QtWidgets.QGroupBox(parent=self.widget_11)
        self.chrome_6.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.chrome_6.setStyleSheet("")
        self.chrome_6.setObjectName("chrome_6")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.chrome_6)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.pushButton_26 = QtWidgets.QPushButton(parent=self.chrome_6)
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout_18.addWidget(self.pushButton_26, 1, 0, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(parent=self.chrome_6)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_18.addWidget(self.lineEdit_18, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.chrome_6, 1, 0, 1, 1)
        self.click_13 = QtWidgets.QGroupBox(parent=self.widget_11)
        self.click_13.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.click_13.setStyleSheet("")
        self.click_13.setObjectName("click_13")
        self.gridLayout_52 = QtWidgets.QGridLayout(self.click_13)
        self.gridLayout_52.setObjectName("gridLayout_52")
        self.lineEdit_77 = QtWidgets.QLineEdit(parent=self.click_13)
        self.lineEdit_77.setText("")
        self.lineEdit_77.setObjectName("lineEdit_77")
        self.gridLayout_52.addWidget(self.lineEdit_77, 4, 0, 1, 2)
        self.pushButton_74 = QtWidgets.QPushButton(parent=self.click_13)
        self.pushButton_74.setObjectName("pushButton_74")
        self.gridLayout_52.addWidget(self.pushButton_74, 5, 0, 1, 2)
        self.lineEdit_80 = QtWidgets.QLineEdit(parent=self.click_13)
        self.lineEdit_80.setText("")
        self.lineEdit_80.setObjectName("lineEdit_80")
        self.gridLayout_52.addWidget(self.lineEdit_80, 3, 0, 1, 2)
        self.gridLayout_17.addWidget(self.click_13, 1, 3, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_17.addItem(spacerItem16, 4, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_17.addItem(spacerItem17, 0, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_17.addItem(spacerItem18, 0, 3, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_17.addItem(spacerItem19, 0, 7, 1, 1)
        self.click_14 = QtWidgets.QGroupBox(parent=self.widget_11)
        self.click_14.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.click_14.setStyleSheet("")
        self.click_14.setObjectName("click_14")
        self.gridLayout_53 = QtWidgets.QGridLayout(self.click_14)
        self.gridLayout_53.setObjectName("gridLayout_53")
        self.pushButton_75 = QtWidgets.QPushButton(parent=self.click_14)
        self.pushButton_75.setObjectName("pushButton_75")
        self.gridLayout_53.addWidget(self.pushButton_75, 2, 0, 1, 1)
        self.pushButton_76 = QtWidgets.QPushButton(parent=self.click_14)
        self.pushButton_76.setObjectName("pushButton_76")
        self.gridLayout_53.addWidget(self.pushButton_76, 2, 1, 1, 1)
        self.lineEdit_81 = QtWidgets.QLineEdit(parent=self.click_14)
        self.lineEdit_81.setText("")
        self.lineEdit_81.setObjectName("lineEdit_81")
        self.gridLayout_53.addWidget(self.lineEdit_81, 1, 0, 1, 2)
        self.gridLayout_17.addWidget(self.click_14, 1, 6, 1, 2)
        self.click_26 = QtWidgets.QGroupBox(parent=self.widget_11)
        self.click_26.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.click_26.setStyleSheet("")
        self.click_26.setObjectName("click_26")
        self.gridLayout_64 = QtWidgets.QGridLayout(self.click_26)
        self.gridLayout_64.setObjectName("gridLayout_64")
        self.lineEdit_98 = QtWidgets.QLineEdit(parent=self.click_26)
        self.lineEdit_98.setText("")
        self.lineEdit_98.setObjectName("lineEdit_98")
        self.gridLayout_64.addWidget(self.lineEdit_98, 1, 0, 1, 2)
        self.pushButton_97 = QtWidgets.QPushButton(parent=self.click_26)
        self.pushButton_97.setObjectName("pushButton_97")
        self.gridLayout_64.addWidget(self.pushButton_97, 2, 0, 1, 2)
        self.gridLayout_17.addWidget(self.click_26, 2, 4, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_17.addItem(spacerItem20, 0, 4, 1, 1)
        self.click_25 = QtWidgets.QGroupBox(parent=self.widget_11)
        self.click_25.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.click_25.setStyleSheet("")
        self.click_25.setObjectName("click_25")
        self.gridLayout_63 = QtWidgets.QGridLayout(self.click_25)
        self.gridLayout_63.setObjectName("gridLayout_63")
        self.pushButton_95 = QtWidgets.QPushButton(parent=self.click_25)
        self.pushButton_95.setObjectName("pushButton_95")
        self.gridLayout_63.addWidget(self.pushButton_95, 2, 1, 1, 1)
        self.pushButton_94 = QtWidgets.QPushButton(parent=self.click_25)
        self.pushButton_94.setObjectName("pushButton_94")
        self.gridLayout_63.addWidget(self.pushButton_94, 2, 0, 1, 1)
        self.lineEdit_95 = QtWidgets.QLineEdit(parent=self.click_25)
        self.lineEdit_95.setText("")
        self.lineEdit_95.setObjectName("lineEdit_95")
        self.gridLayout_63.addWidget(self.lineEdit_95, 1, 0, 1, 1)
        self.lineEdit_96 = QtWidgets.QLineEdit(parent=self.click_25)
        self.lineEdit_96.setText("")
        self.lineEdit_96.setObjectName("lineEdit_96")
        self.gridLayout_63.addWidget(self.lineEdit_96, 1, 1, 1, 1)
        self.gridLayout_17.addWidget(self.click_25, 1, 4, 1, 1)
        self.click_27 = QtWidgets.QGroupBox(parent=self.widget_11)
        self.click_27.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.click_27.setStyleSheet("")
        self.click_27.setObjectName("click_27")
        self.gridLayout_65 = QtWidgets.QGridLayout(self.click_27)
        self.gridLayout_65.setObjectName("gridLayout_65")
        self.lineEdit_99 = QtWidgets.QLineEdit(parent=self.click_27)
        self.lineEdit_99.setText("")
        self.lineEdit_99.setObjectName("lineEdit_99")
        self.gridLayout_65.addWidget(self.lineEdit_99, 1, 0, 1, 2)
        self.pushButton_98 = QtWidgets.QPushButton(parent=self.click_27)
        self.pushButton_98.setObjectName("pushButton_98")
        self.gridLayout_65.addWidget(self.pushButton_98, 2, 0, 1, 2)
        self.gridLayout_17.addWidget(self.click_27, 2, 3, 1, 1)
        self.click_21 = QtWidgets.QGroupBox(parent=self.widget_11)
        self.click_21.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.click_21.setStyleSheet("")
        self.click_21.setObjectName("click_21")
        self.gridLayout_59 = QtWidgets.QGridLayout(self.click_21)
        self.gridLayout_59.setObjectName("gridLayout_59")
        self.pushButton_87 = QtWidgets.QPushButton(parent=self.click_21)
        self.pushButton_87.setObjectName("pushButton_87")
        self.gridLayout_59.addWidget(self.pushButton_87, 2, 0, 1, 1)
        self.pushButton_88 = QtWidgets.QPushButton(parent=self.click_21)
        self.pushButton_88.setObjectName("pushButton_88")
        self.gridLayout_59.addWidget(self.pushButton_88, 2, 1, 1, 1)
        self.lineEdit_82 = QtWidgets.QLineEdit(parent=self.click_21)
        self.lineEdit_82.setText("")
        self.lineEdit_82.setObjectName("lineEdit_82")
        self.gridLayout_59.addWidget(self.lineEdit_82, 1, 0, 1, 2)
        self.gridLayout_17.addWidget(self.click_21, 2, 0, 1, 1)
        self.gridLayout_16.addWidget(self.widget_11, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.widget_12 = QtWidgets.QWidget(parent=self.tab_5)
        self.widget_12.setStyleSheet("QWidget{\n"
"background-color: rgb(206, 206, 206);\n"
"border-radius: 8px;\n"
"font: 8pt \"MS Reference Sans Serif\";\n"
"width: 10px;\n"
"height: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"    border-radius: 7px;\n"
"    border: 2px solid #c2185b; /* Màu viền đỏ hồng đậm */\n"
"    background: linear-gradient(145deg, #ff4081, #c2185b); /* Gradient từ hồng nhạt đến đỏ đậm */\n"
"    color: rgb(0, 0, 0);\n"
"    height: 20px;\n"
"    text-align: center; /* Sửa chính tả từ text-algin thành text-align */\n"
"    font-weight: bold; /* Chữ đậm để tạo ấn tượng */\n"
"    box-shadow: 4px 4px 8px rgba(0, 0, 0, 0.3); /* Đổ bóng cho nút bấm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #f50057; /* Màu viền hồng sáng hơn khi hover */\n"
"    background:#4A569D; /* Gradient sáng hơn khi hover */\n"
"    color: #ffffff; /* Đảm bảo màu chữ vẫn trắng khi hover */\n"
"    box-shadow: 4px 4px 12px rgba(0, 0, 0, 0.4); /* Đổ bóng nổi bật hơn khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: linear-gradient(145deg, #d81b60, #c2185b); /* Gradient tối hơn khi nhấn */\n"
"    border: 2px solid #b71c1c; /* Màu viền đỏ đậm hơn khi nhấn */\n"
"    box-shadow: inset 4px 4px 8px rgba(0, 0, 0, 0.5); /* Hiệu ứng đổ bóng lõm khi nhấn */\n"
"}\n"
"\n"
"\n"
"QGroupBox {\n"
"    border: 2px solid rgb(170, 0, 0);\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 3 10px;\n"
"    background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 16px;\n"
"}\n"
"QLineEdit {\n"
"    border: 1px solid #aaa; /* Đổi màu viền của QLineEdit */\n"
"    border-radius: 5px; /* Làm tròn góc của QLineEdit */\n"
"    padding: 5px; /* Khoảng cách giữa viền và nội dung của QLineEdit */\n"
"    background-color: #333; /* Màu nền của QLineEdit */\n"
"    color: #fff; /* Màu chữ của QLineEdit */\n"
"}")
        self.widget_12.setObjectName("widget_12")
        self.gridLayout_40 = QtWidgets.QGridLayout(self.widget_12)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.click_19 = QtWidgets.QGroupBox(parent=self.widget_12)
        self.click_19.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.click_19.setStyleSheet("")
        self.click_19.setObjectName("click_19")
        self.gridLayout_57 = QtWidgets.QGridLayout(self.click_19)
        self.gridLayout_57.setObjectName("gridLayout_57")
        self.pushButton_83 = QtWidgets.QPushButton(parent=self.click_19)
        self.pushButton_83.setObjectName("pushButton_83")
        self.gridLayout_57.addWidget(self.pushButton_83, 2, 0, 1, 1)
        self.pushButton_84 = QtWidgets.QPushButton(parent=self.click_19)
        self.pushButton_84.setObjectName("pushButton_84")
        self.gridLayout_57.addWidget(self.pushButton_84, 2, 1, 1, 1)
        self.lineEdit_87 = QtWidgets.QLineEdit(parent=self.click_19)
        self.lineEdit_87.setText("")
        self.lineEdit_87.setObjectName("lineEdit_87")
        self.gridLayout_57.addWidget(self.lineEdit_87, 1, 0, 1, 2)
        self.gridLayout_40.addWidget(self.click_19, 1, 2, 1, 1)
        self.click_15 = QtWidgets.QGroupBox(parent=self.widget_12)
        self.click_15.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.click_15.setStyleSheet("")
        self.click_15.setObjectName("click_15")
        self.gridLayout_49 = QtWidgets.QGridLayout(self.click_15)
        self.gridLayout_49.setObjectName("gridLayout_49")
        self.lineEdit_72 = QtWidgets.QLineEdit(parent=self.click_15)
        self.lineEdit_72.setText("")
        self.lineEdit_72.setObjectName("lineEdit_72")
        self.gridLayout_49.addWidget(self.lineEdit_72, 2, 0, 1, 3)
        self.pushButton_69 = QtWidgets.QPushButton(parent=self.click_15)
        self.pushButton_69.setObjectName("pushButton_69")
        self.gridLayout_49.addWidget(self.pushButton_69, 3, 0, 1, 3)
        self.gridLayout_40.addWidget(self.click_15, 1, 0, 1, 1)
        self.click_16 = QtWidgets.QGroupBox(parent=self.widget_12)
        self.click_16.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.click_16.setStyleSheet("")
        self.click_16.setObjectName("click_16")
        self.gridLayout_54 = QtWidgets.QGridLayout(self.click_16)
        self.gridLayout_54.setObjectName("gridLayout_54")
        self.pushButton_77 = QtWidgets.QPushButton(parent=self.click_16)
        self.pushButton_77.setObjectName("pushButton_77")
        self.gridLayout_54.addWidget(self.pushButton_77, 3, 0, 1, 1)
        self.pushButton_78 = QtWidgets.QPushButton(parent=self.click_16)
        self.pushButton_78.setObjectName("pushButton_78")
        self.gridLayout_54.addWidget(self.pushButton_78, 3, 1, 1, 1)
        self.lineEdit_83 = QtWidgets.QLineEdit(parent=self.click_16)
        self.lineEdit_83.setText("")
        self.lineEdit_83.setObjectName("lineEdit_83")
        self.gridLayout_54.addWidget(self.lineEdit_83, 2, 0, 1, 2)
        self.gridLayout_40.addWidget(self.click_16, 1, 1, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_40.addItem(spacerItem21, 2, 0, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_40.addItem(spacerItem22, 0, 0, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_40.addItem(spacerItem23, 0, 1, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_40.addItem(spacerItem24, 0, 2, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_40.addItem(spacerItem25, 0, 3, 1, 1)
        self.gridLayout_21.addWidget(self.widget_12, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.widget_13 = QtWidgets.QWidget(parent=self.tab_6)
        self.widget_13.setStyleSheet("QWidget{\n"
"background-color: rgb(206, 206, 206);\n"
"border-radius: 8px;\n"
"font: 8pt \"MS Reference Sans Serif\";\n"
"width: 10px;\n"
"height: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"    border-radius: 7px;\n"
"    border: 2px solid #c2185b; /* Màu viền đỏ hồng đậm */\n"
"    background: linear-gradient(145deg, #ff4081, #c2185b); /* Gradient từ hồng nhạt đến đỏ đậm */\n"
"    color: rgb(0, 0, 0);\n"
"    height: 20px;\n"
"    text-align: center; /* Sửa chính tả từ text-algin thành text-align */\n"
"    font-weight: bold; /* Chữ đậm để tạo ấn tượng */\n"
"    box-shadow: 4px 4px 8px rgba(0, 0, 0, 0.3); /* Đổ bóng cho nút bấm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #f50057; /* Màu viền hồng sáng hơn khi hover */\n"
"    background:#4A569D; /* Gradient sáng hơn khi hover */\n"
"    color: #ffffff; /* Đảm bảo màu chữ vẫn trắng khi hover */\n"
"    box-shadow: 4px 4px 12px rgba(0, 0, 0, 0.4); /* Đổ bóng nổi bật hơn khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: linear-gradient(145deg, #d81b60, #c2185b); /* Gradient tối hơn khi nhấn */\n"
"    border: 2px solid #b71c1c; /* Màu viền đỏ đậm hơn khi nhấn */\n"
"    box-shadow: inset 4px 4px 8px rgba(0, 0, 0, 0.5); /* Hiệu ứng đổ bóng lõm khi nhấn */\n"
"}\n"
"\n"
"\n"
"QGroupBox {\n"
"    border: 2px solid rgb(153, 0, 153);\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 3 10px;\n"
"    background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 16px;\n"
"}\n"
"QLineEdit {\n"
"    border: 1px solid #aaa; /* Đổi màu viền của QLineEdit */\n"
"    border-radius: 5px; /* Làm tròn góc của QLineEdit */\n"
"    padding: 5px; /* Khoảng cách giữa viền và nội dung của QLineEdit */\n"
"    background-color: #333; /* Màu nền của QLineEdit */\n"
"    color: #fff; /* Màu chữ của QLineEdit */\n"
"}")
        self.widget_13.setObjectName("widget_13")
        self.gridLayout_41 = QtWidgets.QGridLayout(self.widget_13)
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.sleep_14 = QtWidgets.QGroupBox(parent=self.widget_13)
        self.sleep_14.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.sleep_14.setStyleSheet("")
        self.sleep_14.setObjectName("sleep_14")
        self.gridLayout_44 = QtWidgets.QGridLayout(self.sleep_14)
        self.gridLayout_44.setObjectName("gridLayout_44")
        self.pushButton_62 = QtWidgets.QPushButton(parent=self.sleep_14)
        self.pushButton_62.setObjectName("pushButton_62")
        self.gridLayout_44.addWidget(self.pushButton_62, 3, 3, 1, 1)
        self.pushButton_61 = QtWidgets.QPushButton(parent=self.sleep_14)
        self.pushButton_61.setObjectName("pushButton_61")
        self.gridLayout_44.addWidget(self.pushButton_61, 2, 3, 1, 1)
        self.pushButton_89 = QtWidgets.QPushButton(parent=self.sleep_14)
        self.pushButton_89.setObjectName("pushButton_89")
        self.gridLayout_44.addWidget(self.pushButton_89, 3, 1, 1, 1)
        self.pushButton_81 = QtWidgets.QPushButton(parent=self.sleep_14)
        self.pushButton_81.setObjectName("pushButton_81")
        self.gridLayout_44.addWidget(self.pushButton_81, 2, 1, 1, 1)
        self.gridLayout_41.addWidget(self.sleep_14, 1, 2, 1, 1)
        self.click_17 = QtWidgets.QGroupBox(parent=self.widget_13)
        self.click_17.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.click_17.setStyleSheet("")
        self.click_17.setObjectName("click_17")
        self.gridLayout_55 = QtWidgets.QGridLayout(self.click_17)
        self.gridLayout_55.setObjectName("gridLayout_55")
        self.pushButton_79 = QtWidgets.QPushButton(parent=self.click_17)
        self.pushButton_79.setObjectName("pushButton_79")
        self.gridLayout_55.addWidget(self.pushButton_79, 2, 0, 1, 1)
        self.lineEdit_84 = QtWidgets.QLineEdit(parent=self.click_17)
        self.lineEdit_84.setText("")
        self.lineEdit_84.setObjectName("lineEdit_84")
        self.gridLayout_55.addWidget(self.lineEdit_84, 1, 1, 1, 1)
        self.lineEdit_85 = QtWidgets.QLineEdit(parent=self.click_17)
        self.lineEdit_85.setText("")
        self.lineEdit_85.setObjectName("lineEdit_85")
        self.gridLayout_55.addWidget(self.lineEdit_85, 1, 0, 1, 1)
        self.pushButton_80 = QtWidgets.QPushButton(parent=self.click_17)
        self.pushButton_80.setObjectName("pushButton_80")
        self.gridLayout_55.addWidget(self.pushButton_80, 2, 1, 1, 1)
        self.gridLayout_41.addWidget(self.click_17, 1, 0, 1, 1)
        self.click_18 = QtWidgets.QGroupBox(parent=self.widget_13)
        self.click_18.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.click_18.setStyleSheet("")
        self.click_18.setObjectName("click_18")
        self.gridLayout_56 = QtWidgets.QGridLayout(self.click_18)
        self.gridLayout_56.setObjectName("gridLayout_56")
        self.lineEdit_86 = QtWidgets.QLineEdit(parent=self.click_18)
        self.lineEdit_86.setText("")
        self.lineEdit_86.setObjectName("lineEdit_86")
        self.gridLayout_56.addWidget(self.lineEdit_86, 0, 0, 1, 1)
        self.pushButton_82 = QtWidgets.QPushButton(parent=self.click_18)
        self.pushButton_82.setObjectName("pushButton_82")
        self.gridLayout_56.addWidget(self.pushButton_82, 1, 0, 1, 1)
        self.gridLayout_41.addWidget(self.click_18, 1, 3, 1, 1)
        self.click_20 = QtWidgets.QGroupBox(parent=self.widget_13)
        self.click_20.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.click_20.setStyleSheet("")
        self.click_20.setObjectName("click_20")
        self.gridLayout_58 = QtWidgets.QGridLayout(self.click_20)
        self.gridLayout_58.setObjectName("gridLayout_58")
        self.lineEdit_88 = QtWidgets.QLineEdit(parent=self.click_20)
        self.lineEdit_88.setText("")
        self.lineEdit_88.setObjectName("lineEdit_88")
        self.gridLayout_58.addWidget(self.lineEdit_88, 1, 1, 1, 1)
        self.lineEdit_89 = QtWidgets.QLineEdit(parent=self.click_20)
        self.lineEdit_89.setText("")
        self.lineEdit_89.setObjectName("lineEdit_89")
        self.gridLayout_58.addWidget(self.lineEdit_89, 1, 0, 1, 1)
        self.lineEdit_90 = QtWidgets.QLineEdit(parent=self.click_20)
        self.lineEdit_90.setText("")
        self.lineEdit_90.setObjectName("lineEdit_90")
        self.gridLayout_58.addWidget(self.lineEdit_90, 0, 0, 1, 1)
        self.lineEdit_91 = QtWidgets.QLineEdit(parent=self.click_20)
        self.lineEdit_91.setText("")
        self.lineEdit_91.setObjectName("lineEdit_91")
        self.gridLayout_58.addWidget(self.lineEdit_91, 0, 1, 1, 1)
        self.pushButton_90 = QtWidgets.QPushButton(parent=self.click_20)
        self.pushButton_90.setObjectName("pushButton_90")
        self.gridLayout_58.addWidget(self.pushButton_90, 2, 1, 1, 1)
        self.pushButton_85 = QtWidgets.QPushButton(parent=self.click_20)
        self.pushButton_85.setObjectName("pushButton_85")
        self.gridLayout_58.addWidget(self.pushButton_85, 2, 0, 1, 1)
        self.pushButton_86 = QtWidgets.QPushButton(parent=self.click_20)
        self.pushButton_86.setObjectName("pushButton_86")
        self.gridLayout_58.addWidget(self.pushButton_86, 3, 0, 1, 2)
        self.gridLayout_41.addWidget(self.click_20, 1, 1, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_41.addItem(spacerItem26, 4, 0, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_41.addItem(spacerItem27, 0, 0, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_41.addItem(spacerItem28, 0, 1, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_41.addItem(spacerItem29, 0, 2, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_41.addItem(spacerItem30, 0, 3, 1, 1)
        self.gridLayout_22.addWidget(self.widget_13, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.widget_16 = QtWidgets.QWidget(parent=self.tab_2)
        self.widget_16.setStyleSheet("QWidget{\n"
"background-color: rgb(206, 206, 206);\n"
"border-radius: 8px;\n"
"font: 8pt \"MS Reference Sans Serif\";\n"
"width: 10px;\n"
"height: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"    border-radius: 7px;\n"
"    border: 2px solid #c2185b; /* Màu viền đỏ hồng đậm */\n"
"    background: linear-gradient(145deg, #ff4081, #c2185b); /* Gradient từ hồng nhạt đến đỏ đậm */\n"
"    color: rgb(0, 0, 0);\n"
"    height: 20px;\n"
"    text-align: center; /* Sửa chính tả từ text-algin thành text-align */\n"
"    font-weight: bold; /* Chữ đậm để tạo ấn tượng */\n"
"    box-shadow: 4px 4px 8px rgba(0, 0, 0, 0.3); /* Đổ bóng cho nút bấm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #f50057; /* Màu viền hồng sáng hơn khi hover */\n"
"    background:#4A569D; /* Gradient sáng hơn khi hover */\n"
"    color: #ffffff; /* Đảm bảo màu chữ vẫn trắng khi hover */\n"
"    box-shadow: 4px 4px 12px rgba(0, 0, 0, 0.4); /* Đổ bóng nổi bật hơn khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: linear-gradient(145deg, #d81b60, #c2185b); /* Gradient tối hơn khi nhấn */\n"
"    border: 2px solid #b71c1c; /* Màu viền đỏ đậm hơn khi nhấn */\n"
"    box-shadow: inset 4px 4px 8px rgba(0, 0, 0, 0.5); /* Hiệu ứng đổ bóng lõm khi nhấn */\n"
"}\n"
"\n"
"\n"
"QGroupBox {\n"
"    border: 2px solid rgb(153, 0, 153);\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 3 10px;\n"
"    background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 16px;\n"
"}\n"
"QLineEdit {\n"
"    border: 1px solid #aaa; /* Đổi màu viền của QLineEdit */\n"
"    border-radius: 5px; /* Làm tròn góc của QLineEdit */\n"
"    padding: 5px; /* Khoảng cách giữa viền và nội dung của QLineEdit */\n"
"    background-color: #333; /* Màu nền của QLineEdit */\n"
"    color: #fff; /* Màu chữ của QLineEdit */\n"
"}")
        self.widget_16.setObjectName("widget_16")
        self.gridLayout_43 = QtWidgets.QGridLayout(self.widget_16)
        self.gridLayout_43.setObjectName("gridLayout_43")
        spacerItem31 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_43.addItem(spacerItem31, 4, 0, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_43.addItem(spacerItem32, 0, 0, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_43.addItem(spacerItem33, 0, 1, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_43.addItem(spacerItem34, 0, 2, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_43.addItem(spacerItem35, 0, 3, 1, 1)
        self.click_24 = QtWidgets.QGroupBox(parent=self.widget_16)
        self.click_24.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.click_24.setStyleSheet("")
        self.click_24.setObjectName("click_24")
        self.gridLayout_62 = QtWidgets.QGridLayout(self.click_24)
        self.gridLayout_62.setObjectName("gridLayout_62")
        self.pushButton_100 = QtWidgets.QPushButton(parent=self.click_24)
        self.pushButton_100.setObjectName("pushButton_100")
        self.gridLayout_62.addWidget(self.pushButton_100, 1, 2, 1, 1)
        self.lineEdit_102 = QtWidgets.QLineEdit(parent=self.click_24)
        self.lineEdit_102.setText("")
        self.lineEdit_102.setObjectName("lineEdit_102")
        self.gridLayout_62.addWidget(self.lineEdit_102, 0, 0, 1, 3)
        self.pushButton_99 = QtWidgets.QPushButton(parent=self.click_24)
        self.pushButton_99.setObjectName("pushButton_99")
        self.gridLayout_62.addWidget(self.pushButton_99, 1, 0, 1, 1)
        self.pushButton_101 = QtWidgets.QPushButton(parent=self.click_24)
        self.pushButton_101.setObjectName("pushButton_101")
        self.gridLayout_62.addWidget(self.pushButton_101, 1, 1, 1, 1)
        self.gridLayout_43.addWidget(self.click_24, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.widget_16, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.gridLayout_15.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_15, 1, 0, 2, 1)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_23.addItem(spacerItem36, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.system)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_8 = QtWidgets.QWidget(parent=self.page_2)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_6.addItem(spacerItem37, 0, 5, 1, 1)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_6.addItem(spacerItem38, 0, 1, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_6.addItem(spacerItem39, 0, 7, 1, 1)
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_6.addItem(spacerItem40, 0, 2, 1, 1)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_6.addItem(spacerItem41, 0, 6, 1, 1)
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=self.widget_8)
        self.calendarWidget.setStyleSheet("QCalendarWidget {\n"
"    background-color: #2c3e50; /* Màu nền */\n"
"    border: 1px solid #34495e; /* Viền xung quanh */\n"
"    border-radius: 10px; /* Bo tròn góc */\n"
"    padding: 10px; /* Khoảng cách bên trong */\n"
"}\n"
"\n"
"QCalendarWidget QAbstractItemView {\n"
"    background-color: #34495e; /* Màu nền của ngày */\n"
"    selection-background-color: #2980b9; /* Màu nền khi chọn */\n"
"    selection-color: white; /* Màu chữ khi chọn */\n"
"    alternate-background-color: #2c3e50; /* Màu nền của các hàng lẻ */\n"
"    border-radius: 5px; /* Bo tròn góc */\n"
"}\n"
"\n"
"QCalendarWidget QHeaderView::section {\n"
"    background-color: #34495e; /* Màu nền của tiêu đề tuần */\n"
"    color: white; /* Màu chữ */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    border: 1px solid #2c3e50; /* Viền của tiêu đề tuần */\n"
"    border-radius: 5px; /* Bo tròn góc */\n"
"}\n"
"\n"
"QCalendarWidget QToolButton {\n"
"    background-color: #2980b9; /* Màu nền của các nút điều khiển */\n"
"    color: white; /* Màu chữ */\n"
"    border: none; /* Không có viền */\n"
"    border-radius: 5px; /* Bo tròn góc */\n"
"}\n"
"\n"
"QCalendarWidget QToolButton:hover {\n"
"    background-color: #3498db; /* Màu nền khi di chuột qua */\n"
"}\n"
"\n"
"QCalendarWidget QToolButton:pressed {\n"
"    background-color: #1f77d1; /* Màu nền khi nhấn */\n"
"}\n"
"")
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout_6.addWidget(self.calendarWidget, 1, 1, 1, 2)
        spacerItem42 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_6.addItem(spacerItem42, 5, 0, 1, 1)
        spacerItem43 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_6.addItem(spacerItem43, 1, 0, 1, 1)
        spacerItem44 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_6.addItem(spacerItem44, 4, 0, 1, 1)
        spacerItem45 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_6.addItem(spacerItem45, 2, 0, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.widget_8)
        self.scrollArea_2.setStyleSheet("QScrollArea {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 2px solid rgb(0, 80, 118);\n"
"    color: rgb(0, 0, 0);\n"
"    selection-background-color: rgb(0, 128, 255);\n"
"    selection-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(230, 230, 230); /* Màu nền thanh cuộn */\n"
"    width: 12px;\n"
"    margin: 15px 0 15px 0; /* Khoảng cách giữa đầu và cuối thanh cuộn */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: rgb(0, 80, 118); /* Màu thanh cuộn */\n"
"    min-height: 20px; /* Chiều cao tối thiểu của thanh cuộn */\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(230, 230, 230); /* Màu nền thanh cuộn ngang */\n"
"    height: 12px;\n"
"    margin: 0 15px 0 15px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(0, 80, 118); /* Màu thanh cuộn ngang */\n"
"    min-width: 20px; /* Chiều rộng tối thiểu của thanh cuộn ngang */\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: none;\n"
"    width: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"QPushButton {\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(0, 128, 255); /* Thay đổi màu sắc và độ dày của border */\n"
"    padding: 10px; /* Thêm padding để tạo khoảng cách giữa nội dung và viền */\n"
"    \n"
"    \n"
"    \n"
"    font: 57 9pt \"Dubai Medium\";\n"
"}\n"
"")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1239, 574))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.scrollAreaWidgetContents)
        self.tableWidget_2.setStyleSheet("QTableWidget {\n"
"    background-color: #2e2e2e; /* Màu nền của table */\n"
"    border: none;\n"
"    color: #e0e0e0; /* Màu chữ */\n"
"    gridline-color: #555555; /* Màu của các đường lưới */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #5a5a5a; /* Màu nền khi chọn một ô */\n"
"    color: #ffffff; /* Màu chữ khi chọn một ô */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #333333; /* Màu nền của tiêu đề cột */\n"
"    color: #ffffff; /* Màu chữ của tiêu đề cột */\n"
"    padding: 5px; /* Khoảng cách padding */\n"
"    border: 1px solid #444444; /* Đường viền của tiêu đề cột */\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #333333; /* Màu nền của góc table */\n"
"    border: 1px solid #444444; /* Đường viền của góc table */\n"
"}\n"
"QHeaderView::section {\n"
"        border: none;  /* Loại bỏ viền cho các tiêu đề cột */\n"
"    }\n"
"QTableWidget::item:selected {\n"
"        background-color: transparent;  /* Loại bỏ màu nền khi mục được chọn */\n"
"    }\n"
"")
        self.tableWidget_2.setShowGrid(False)
        self.tableWidget_2.setGridStyle(QtCore.Qt.PenStyle.NoPen)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(24)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(23, item)
        self.gridLayout_10.addWidget(self.tableWidget_2, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_6.addWidget(self.scrollArea_2, 2, 1, 4, 9)
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_6.addItem(spacerItem46, 0, 3, 1, 1)
        spacerItem47 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_6.addItem(spacerItem47, 0, 4, 1, 1)
        self.gridLayout_4.addWidget(self.widget_8, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(parent=self.page)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("img/comingsoon.svg"))
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout_2.addWidget(self.widget_3, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.pushButton_9.toggled['bool'].connect(self.widget.setHidden) # type: ignore
        self.pushButton_9.toggled['bool'].connect(self.widget_2.setVisible) # type: ignore
        self.pushButton_4.toggled['bool'].connect(self.pushButton_8.setChecked) # type: ignore
        self.pushButton_3.toggled['bool'].connect(self.pushButton_7.setChecked) # type: ignore
        self.pushButton_2.toggled['bool'].connect(self.pushButton_6.setChecked) # type: ignore
        self.pushButton.toggled['bool'].connect(self.pushButton_5.setChecked) # type: ignore
        self.pushButton_5.toggled['bool'].connect(self.pushButton.setChecked) # type: ignore
        self.pushButton_6.toggled['bool'].connect(self.pushButton_2.setChecked) # type: ignore
        self.pushButton_7.toggled['bool'].connect(self.pushButton_3.setChecked) # type: ignore
        self.pushButton_8.toggled['bool'].connect(self.pushButton_4.setChecked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Iart VPSControl Pro "))
        self.pushButton_5.setText(_translate("MainWindow", "Dashboard     "))
        self.pushButton_6.setText(_translate("MainWindow", "Scripts"))
        self.pushButton_7.setText(_translate("MainWindow", "Schedule"))
        self.pushButton_8.setText(_translate("MainWindow", "Setting"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Hostname"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "IP Address"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Location"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Script"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "View Sceen"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Setting"))
        self.pushButton_11.setText(_translate("MainWindow", "Chọn tất cả"))
        self.pushButton_12.setText(_translate("MainWindow", "Set kịch bản"))
        self.pushButton_13.setText(_translate("MainWindow", "Dừng lại"))
        self.pushButton_14.setText(_translate("MainWindow", "Bắt đầu"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_22.setText(_translate("MainWindow", "Chạy Thử"))
        self.pushButton_23.setText(_translate("MainWindow", "Quay Lại"))
        self.pushButton_25.setText(_translate("MainWindow", "Xóa Hết"))
        self.pushButton_24.setText(_translate("MainWindow", "Lưu Script"))
        self.chrome_8.setTitle(_translate("MainWindow", "Delay Step"))
        self.pushButton_28.setText(_translate("MainWindow", "Add"))
        self.lineEdit_20.setPlaceholderText(_translate("MainWindow", "s"))
        self.lineEdit_21.setPlaceholderText(_translate("MainWindow", "s"))
        self.label_6.setText(_translate("MainWindow", "+-"))
        self.chrome_7.setTitle(_translate("MainWindow", "Web Default"))
        self.pushButton_27.setText(_translate("MainWindow", "Add"))
        self.lineEdit_19.setPlaceholderText(_translate("MainWindow", "Go to link url"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "General"))
        self.chrome_6.setTitle(_translate("MainWindow", "Chrome New"))
        self.pushButton_26.setText(_translate("MainWindow", "Add"))
        self.lineEdit_18.setPlaceholderText(_translate("MainWindow", "Proxy"))
        self.click_13.setTitle(_translate("MainWindow", "Chrome Profile"))
        self.lineEdit_77.setPlaceholderText(_translate("MainWindow", "Profile Xpath"))
        self.pushButton_74.setText(_translate("MainWindow", "Add"))
        self.lineEdit_80.setPlaceholderText(_translate("MainWindow", "Proxy"))
        self.click_14.setTitle(_translate("MainWindow", "Add Cookie"))
        self.pushButton_75.setText(_translate("MainWindow", "Load"))
        self.pushButton_76.setText(_translate("MainWindow", "Add"))
        self.lineEdit_81.setPlaceholderText(_translate("MainWindow", "Cookie Xpath"))
        self.click_26.setTitle(_translate("MainWindow", "Zoom In/Out"))
        self.lineEdit_98.setPlaceholderText(_translate("MainWindow", "% Zoom in/out"))
        self.pushButton_97.setText(_translate("MainWindow", "Add"))
        self.click_25.setTitle(_translate("MainWindow", "Resize Chrome"))
        self.pushButton_95.setText(_translate("MainWindow", "Add"))
        self.pushButton_94.setText(_translate("MainWindow", "Full"))
        self.lineEdit_95.setPlaceholderText(_translate("MainWindow", "Width"))
        self.lineEdit_96.setPlaceholderText(_translate("MainWindow", "Height"))
        self.click_27.setTitle(_translate("MainWindow", "Go Url"))
        self.lineEdit_99.setPlaceholderText(_translate("MainWindow", "Go to link url"))
        self.pushButton_98.setText(_translate("MainWindow", "Add"))
        self.click_21.setTitle(_translate("MainWindow", "Add Extension"))
        self.pushButton_87.setText(_translate("MainWindow", "Load"))
        self.pushButton_88.setText(_translate("MainWindow", "Add"))
        self.lineEdit_82.setPlaceholderText(_translate("MainWindow", ".crx file"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Auto Web"))
        self.click_19.setTitle(_translate("MainWindow", "Multi Press"))
        self.pushButton_83.setText(_translate("MainWindow", "Get"))
        self.pushButton_84.setText(_translate("MainWindow", "Add"))
        self.lineEdit_87.setPlaceholderText(_translate("MainWindow", "Press1 Press2"))
        self.click_15.setTitle(_translate("MainWindow", "Keyboard"))
        self.lineEdit_72.setPlaceholderText(_translate("MainWindow", "Text"))
        self.pushButton_69.setText(_translate("MainWindow", "Add"))
        self.click_16.setTitle(_translate("MainWindow", "Press"))
        self.pushButton_77.setText(_translate("MainWindow", "Get"))
        self.pushButton_78.setText(_translate("MainWindow", "Add"))
        self.lineEdit_83.setPlaceholderText(_translate("MainWindow", "Press"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Keyboard"))
        self.sleep_14.setTitle(_translate("MainWindow", "Click Mouse"))
        self.pushButton_62.setText(_translate("MainWindow", "H.Right"))
        self.pushButton_61.setText(_translate("MainWindow", "Right"))
        self.pushButton_89.setText(_translate("MainWindow", "H.Left"))
        self.pushButton_81.setText(_translate("MainWindow", "Left"))
        self.click_17.setTitle(_translate("MainWindow", "Move Point"))
        self.pushButton_79.setText(_translate("MainWindow", "Get"))
        self.lineEdit_84.setPlaceholderText(_translate("MainWindow", "Y"))
        self.lineEdit_85.setPlaceholderText(_translate("MainWindow", "X"))
        self.pushButton_80.setText(_translate("MainWindow", "Add"))
        self.click_18.setTitle(_translate("MainWindow", "Scroll"))
        self.lineEdit_86.setPlaceholderText(_translate("MainWindow", "+- Scroll Height"))
        self.pushButton_82.setText(_translate("MainWindow", "Add"))
        self.click_20.setTitle(_translate("MainWindow", "Move Boundary"))
        self.lineEdit_88.setPlaceholderText(_translate("MainWindow", "Height"))
        self.lineEdit_89.setPlaceholderText(_translate("MainWindow", "Width"))
        self.lineEdit_90.setPlaceholderText(_translate("MainWindow", "X"))
        self.lineEdit_91.setPlaceholderText(_translate("MainWindow", "Y"))
        self.pushButton_90.setText(_translate("MainWindow", "Paste"))
        self.pushButton_85.setText(_translate("MainWindow", "Crop"))
        self.pushButton_86.setText(_translate("MainWindow", "Add"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Mouse"))
        self.click_24.setTitle(_translate("MainWindow", "Move Mouse In Image"))
        self.pushButton_100.setText(_translate("MainWindow", "Add"))
        self.lineEdit_102.setPlaceholderText(_translate("MainWindow", "Base64 string"))
        self.pushButton_99.setText(_translate("MainWindow", "Crop"))
        self.pushButton_101.setText(_translate("MainWindow", "Paste"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "AI"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0h"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1h"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2h"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3h"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "4h"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "5h"))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "6h"))
        item = self.tableWidget_2.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "7h"))
        item = self.tableWidget_2.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "8h"))
        item = self.tableWidget_2.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "9h"))
        item = self.tableWidget_2.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "10h"))
        item = self.tableWidget_2.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "11h"))
        item = self.tableWidget_2.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "12h"))
        item = self.tableWidget_2.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "13h"))
        item = self.tableWidget_2.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "14h"))
        item = self.tableWidget_2.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "15h"))
        item = self.tableWidget_2.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "16h"))
        item = self.tableWidget_2.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "17h"))
        item = self.tableWidget_2.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "18h"))
        item = self.tableWidget_2.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "19h"))
        item = self.tableWidget_2.verticalHeaderItem(20)
        item.setText(_translate("MainWindow", "20h"))
        item = self.tableWidget_2.verticalHeaderItem(21)
        item.setText(_translate("MainWindow", "21h"))
        item = self.tableWidget_2.verticalHeaderItem(22)
        item.setText(_translate("MainWindow", "22h"))
        item = self.tableWidget_2.verticalHeaderItem(23)
        item.setText(_translate("MainWindow", "23h"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
